package public

var RuleDatas = []RuleDataType{
	{"深信服防火墙类产品", "code", "", "(SANGFOR FW)"},
	{"BigIP", "headers", "", "(BigIP|BIGipServer)"},
	{"Shiro", "headers", "", "(=deleteMe|rememberMe=)"},
	{"Portainer(Docker管理)", "code", "", "(portainer.updatePassword|portainer.init.admin)"},
	{"Gogs简易Git服务", "cookie", "", "(i_like_gogs)"},
	{"Gitea简易Git服务", "cookie", "", "(i_like_gitea)"},
	{"Nexus", "code", "", "(Nexus Repository Manager)"},
	{"Nexus", "cookie", "", "(NX-ANTI-CSRF-TOKEN)"},
	{"Harbor", "code", "", "(<title>Harbor</title>)"},
	{"Harbor", "cookie", "", "(harbor-lang)"},
	{"禅道", "code", "", "(/theme/default/images/main/zt-logo.png)"},
	{"禅道", "cookie", "", "(zentaosid)"},
	{"协众OA", "code", "", "(Powered by 协众OA)"},
	{"协众OA", "cookie", "", "(CNOAOASESSID)"},
	{"xxl-job", "code", "", "(分布式任务调度平台XXL-JOB)"},
	{"atmail-WebMail", "cookie", "", "(atmail6)"},
	{"atmail-WebMail", "code", "", "(/index.php/mail/auth/processlogin|Powered by Atmail)"},
	{"weblogic", "code", "", "(/console/framework/skins/wlsconsole/images/login_WebLogic_branding.png|Welcome to Weblogic Application Server|<i>Hypertext Transfer Protocol -- HTTP/1.1</i>)"},
	{"致远OA", "code", "", "(/seeyon/common/|/seeyon/USER-DATA/IMAGES/LOGIN/login.gif)"},
	{"discuz", "code", "", "(content=\"Discuz! X\")"},
	{"Typecho", "code", "", "(Typecho</a>)"},
	{"金蝶EAS", "code", "", "(easSessionId)"},
	{"phpMyAdmin", "cookie", "", "(pma_lang|phpMyAdmin)"},
	{"phpMyAdmin", "code", "", "(/themes/pmahomme/img/logo_right.png)"},
	{"H3C-AM8000", "code", "", "(AM8000)"},
	{"360企业版", "code", "", "(360EntWebAdminMD5Secret)"},
	{"H3C公司产品", "code", "", "(service@h3c.com)"},
	{"H3C ICG 1000", "code", "", "(ICG 1000系统管理)"},
	{"Citrix-Metaframe", "code", "", "(window.location=\"/Citrix/MetaFrame)"},
	{"H3C ER5100", "code", "", "(ER5100系统管理)"},
	{"阿里云CDN", "code", "", "(cdn.aliyuncs.com)"},
	{"CISCO_EPC3925", "code", "", "(Docsis_system)"},
	{"CISCO ASR", "code", "", "(CISCO ASR)"},
	{"H3C ER3200", "code", "", "(ER3200系统管理)"},
	{"万户ezOFFICE", "headers", "", "(LocLan)"},
	{"万户网络", "code", "", "(css/css_whir.css)"},
	{"Spark_Master", "code", "", "(Spark Master at)"},
	{"华为_HUAWEI_SRG2220", "code", "", "(HUAWEI SRG2220)"},
	{"蓝凌OA", "code", "", "(/scripts/jquery.landray.common.js)"},
	{"华为 NetOpen", "code", "", "(/netopen/theme/css/inFrame.css)"},
	{"Citrix-Web-PN-Server", "code", "", "(Citrix Web PN Server)"},
	{"juniper_vpn", "code", "", "(welcome.cgi?p=logo|/images/logo_juniper_reversed.gif)"},
	{"Nagios", "headers", "", "(Nagios Access)"},
	{"H3C ER8300", "code", "", "(ER8300系统管理)"},
	{"Citrix-Access-Gateway", "code", "", "(Citrix Access Gateway)"},
	{"华为 MCU", "code", "", "(McuR5-min.js)"},
	{"TP-LINK Wireless WDR3600", "code", "", "(TP-LINK Wireless WDR3600)"},
	{"泛微OA", "headers", "", "(ecology_JSessionid)"},
	{"泛微OA", "code", "", "(/spa/portal/public/index.js)"},
	{"华为_HUAWEI_ASG2050", "code", "", "(HUAWEI ASG2050)"},
	{"Citrix-XenServer", "code", "", "(Citrix Systems, Inc. XenServer)"},
	{"H3C ER2100V2", "code", "", "(ER2100V2系统管理)"},
	{"zabbix", "cookie", "", "(zbx_sessionid)"},
	{"zabbix", "code", "", "(images/general/zabbix.ico|Zabbix SIA)"},
	{"CISCO_VPN", "headers", "", "(webvpn)"},
	{"360站长平台", "code", "", "(360-site-verification)"},
	{"H3C ER3108GW", "code", "", "(ER3108GW系统管理)"},
	{"o2security_vpn", "headers", "", "(client_param=install_active)"},
	{"H3C ER3260G2", "code", "", "(ER3260G2系统管理)"},
	{"H3C ICG1000", "code", "", "(ICG1000系统管理)"},
	{"CISCO-CX20", "code", "", "(CISCO-CX20)"},
	{"H3C ER5200", "code", "", "(ER5200系统管理)"},
	{"linksys-vpn-bragap14-parintins", "code", "", "(linksys-vpn-bragap14-parintins)"},
	{"H3C ER3100", "code", "", "(ER3100系统管理)"},
	{"H3C-SecBlade-FireWall", "code", "", "(js/MulPlatAPI.js)"},
	{"360webfacil_360WebManager", "code", "", "(publico/template/)"},
	{"Citrix_Netscaler", "code", "", "(ns_af)"},
	{"H3C ER6300G2", "code", "", "(ER6300G2系统管理)"},
	{"H3C ER3260", "code", "", "(ER3260系统管理)"},
	{"华为_HUAWEI_SRG3250", "code", "", "(HUAWEI SRG3250)"},
	{"exchange", "code", "", "(/owa/auth.owa)"},
	{"Spark_Worker", "code", "", "(Spark Worker at)"},
	{"H3C ER3108G", "code", "", "(ER3108G系统管理)"},
	{"Citrix-ConfProxy", "code", "", "(confproxy)"},
	{"H3C ER5200G2", "code", "", "(ER5200G2系统管理)"},
	{"华为（HUAWEI）安全设备", "code", "", "(sweb-lib/resource/)"},
	{"华为（HUAWEI）USG", "code", "", "(UI_component/commonDefine/UI_regex_define.js)"},
	{"H3C ER6300", "code", "", "(ER6300系统管理)"},
	{"华为_HUAWEI_ASG2100", "code", "", "(HUAWEI ASG2100)"},
	{"TP-Link 3600 DD-WRT", "code", "", "(TP-Link 3600 DD-WRT)"},
	{"NETGEAR WNDR3600", "code", "", "(NETGEAR WNDR3600)"},
	{"H3C ER2100", "code", "", "(ER2100系统管理)"},
	{"jira", "code", "", "(jira.webresources)"},
	{"金和协同管理平台", "code", "", "(金和协同管理平台)"},
	{"Citrix-NetScaler", "code", "", "(NS-CACHE)"},
	{"linksys-vpn", "headers", "", "(linksys-vpn)"},
	{"通达OA", "code", "", "(/static/images/tongda.ico|http://www.tongda2000.com|通达OA移动版)"},
	{"华为（HUAWEI）Secoway设备", "code", "", "(Secoway)"},
	{"华为_HUAWEI_SRG1220", "code", "", "(HUAWEI SRG1220)"},
	{"H3C ER2100n", "code", "", "(ER2100n系统管理)"},
	{"H3C ER8300G2", "code", "", "(ER8300G2系统管理)"},
	{"金蝶政务GSiS", "code", "", "(/kdgs/script/kdgs.js)"},
	{"Jboss", "code", "", "(Welcome to JBoss|jboss.css)"},
	{"Jboss", "headers", "", "(JBoss)"},
	{"泛微E-mobile", "code", "", "(Weaver E-mobile|weaver,e-mobile)"},
	{"泛微E-mobile", "headers", "", "(EMobileServer)"},
	{"齐治堡垒机", "code", "", "(logo-icon-ico72.png|resources/themes/images/logo-login.png)"},
	{"ThinkPHP", "headers", "", "(ThinkPHP)"},
	{"ThinkPHP", "code", "", "(/Public/static/js/)"},
	{"weaver-ebridge", "code", "", "(e-Bridge,http://wx.weaver)"},
	{"Laravel", "headers", "", "(laravel_session)"},
	{"DWR", "code", "", "(dwr/engine.js)"},
	{"swagger_ui", "code", "", "(swagger-ui/css|\"swagger\":|swagger-ui.min.js)"},
	{"大汉版通发布系统", "code", "", "(大汉版通发布系统|大汉网络)"},
	{"druid", "code", "", "(druid.index|DruidDrivers|DruidVersion|Druid Stat Index)"},
	{"Jenkins", "code", "", "(Jenkins)"},
	{"红帆OA", "code", "", "(iOffice)"},
	{"VMware vSphere", "code", "", "(VMware vSphere)"},
	{"打印机", "code", "", "(打印机|media/canon.gif)"},
	{"finereport", "code", "", "(isSupportForgetPwd|FineReport,Web Reporting Tool)"},
	{"蓝凌OA", "code", "", "(蓝凌软件|StylePath:\"/resource/style/default/\"|/resource/customization)"},
	{"GitLab", "code", "", "(href=\"https://about.gitlab.com/)"},
	{"用友", "code", "", "(YONYOU NC | /Client/Uclient/UClient.dmg|iufo/web/css/menu.css|/System/Login/Login.asp?AppID=|/nc/servlet/nc.ui.iufo.login.Index)"},
	{"Jquery-1.7.2", "code", "", "(/webui/js/jquerylib/jquery-1.7.2.min.js)"},
	{"Hadoop Applications", "code", "", "(/cluster/app/application)"},
	{"海昌OA", "code", "", "(/loginmain4/js/jquery.min.js)"},
	{"帆软报表", "code", "", "(WebReport/login.html|ReportServer)"},
	{"帆软报表", "headers", "", "(数据决策系统)"},
	{"华夏ERP", "headers", "", "(华夏ERP)"},
	{"金和OA", "cookie", "", "(ASPSESSIONIDSSCDTDBS)"},
	{"久其财务报表", "code", "", "(netrep/login.jsp|/netrep/intf)"},
	{"若依管理系统", "code", "", "(ruoyi/login.js|ruoyi/js/ry-ui.js)"},
	{"启莱OA", "code", "", "(js/jQselect.js)"},
	{"智慧校园管理系统", "code", "", "(DC_Login/QYSignUp)"},
	{"JQuery-1.7.2", "code", "", "(webui/js/jquerylib/jquery-1.7.2.min.js)"},
	{"浪潮 ClusterEngineV4.0", "code", "", "(0;url=module/login/login.html)"},
	{"会捷通云视讯平台", "code", "", "(him/api/rest/v1.0/node/role|him.app)"},
	{"源码泄露账号密码 F12查看", "code", "", "(get_dkey_passwd)"},
	{"Smartbi Insight", "code", "", "(smartbi.gcf.gcfutil)"},
	{"汉王人脸考勤管理系统", "code", "", "(汉王人脸考勤管理系统|/Content/image/hanvan.png|/Content/image/hvicon.ico)"},
	{"亿赛通-电子文档安全管理系统", "code", "", "(电子文档安全管理系统|/CDGServer3/index.jsp|/CDGServer3/SysConfig.jsp|/CDGServer3/help/getEditionInfo.jsp)"},
	{"天融信 TopApp-LB 负载均衡系统", "code", "", "(TopApp-LB 负载均衡系统)"},
	{"中新金盾信息安全管理系统", "code", "", "(中新金盾信息安全管理系统|中新网络信息安全股份有限公司)"},
	{"好视通", "code", "", "(深圳银澎云计算有限公司|itunes.apple.com/us/app/id549407870|hao-shi-tong-yun-hui-yi-yuan)"},
	{"蓝海卓越计费管理系统", "code", "", "(蓝海卓越计费管理系统|星锐蓝海网络科技有限公司)"},
	{"和信创天云桌面系统", "code", "", "(和信下一代云桌面VENGD|/vesystem/index.php)"},
	{"金山", "code", "", "(北京猎鹰安全科技有限公司|金山终端安全系统V9.0Web控制台|北京金山安全管理系统技术有限公司|金山V8)"},
	{"WIFISKY-7层流控路由器", "code", "", "(深圳市领空技术有限公司|WIFISKY 7层流控路由器)"},
	{"MetInfo-米拓建站", "code", "", "(MetInfo|/skin/style/metinfo.css|/skin/style/metinfo-v2.css)"},
	{"IBM-Lotus-Domino", "code", "", "(/mailjump.nsf|/domcfg.nsf|/names.nsf|/homepage.nsf)"},
	{"APACHE-kylin", "code", "", "(url=kylin)"},
	{"C-Lodop打印服务系统", "code", "", "(/CLodopfuncs.js|www.c-lodop.com)"},
	{"ATLASSIAN-Confluence", "code", "", "(Atlassian Confluence)"},
	{"HFS", "code", "", "(href=\"http://www.rejetto.com/hfs/)"},
	{"Jellyfin", "code", "", "(content=\"http://jellyfin.org\")"},
	{"FIT2CLOUD-JumpServer-堡垒机", "code", "", "(<title>JumpServer</title>)"},
	{"Alibaba Nacos", "code", "", "(<title>Nacos</title>)"},
	{"Nagios", "headers", "", "(nagios admin)"},
	{"Pulse Connect Secure", "code", "", "(/dana-na/imgs/space.gif)"},
	{"h5ai", "code", "", "(powered by h5ai)"},
	{"jeesite", "cookie", "", "(jeesite.session.id)"},
	{"拓尔思SSO", "cookie", "", "(trsidsssosessionid)"},
	{"拓尔思WCMv7/6", "cookie", "", "(com.trs.idm.coSessionId)"},
	{"天融信脆弱性扫描与管理系统", "code", "", "(/js/report/horizontalReportPanel.js)"},
	{"天融信网络审计系统", "code", "", "(onclick=dlg_download())"},
	{"天融信日志收集与分析系统", "code", "", "(天融信日志收集与分析系统)"},
	{"URP教务系统", "code", "", "(北京清元优软科技有限公司)"},
	{"科来RAS", "code", "", "(科来软件 版权所有|i18ninit.min.js)"},
	{"正方OA", "code", "", "(zfoausername)"},
	{"希尔OA", "code", "", "(/heeroa/login.do)"},
	{"泛普建筑工程施工OA", "code", "", "(/dwr/interface/LoginService.js)"},
	{"中望OA", "code", "", "(/IMAGES/default/first/xtoa_logo.png|/app_qjuserinfo/qjuserinfoadd.jsp)"},
	{"海天OA", "code", "", "(HTVOS.js)"},
	{"信达OA", "code", "", "(http://www.xdoa.cn</a>)"},
	{"任我行CRM", "code", "", "(CRM_LASTLOGINUSERKEY)"},
	{"Spammark邮件信息安全网关", "code", "", "(/cgi-bin/spammark?empty=1)"},
	{"winwebmail", "code", "", "(WinWebMail Server|images/owin.css)"},
	{"浪潮政务系统", "code", "", "(LangChao.ECGAP.OutPortal|OnlineQuery/QueryList.aspx)"},
	{"天融信防火墙", "code", "", "(/cgi/maincgi.cgi)"},
	{"网神防火墙", "code", "", "(css/lsec/login.css)"},
	{"帕拉迪统一安全管理和综合审计系统", "code", "", "(module/image/pldsec.css)"},
	{"蓝盾BDWebGuard", "code", "", "(BACKGROUND: url(images/loginbg.jpg) #e5f1fc)"},
	{"Huawei SMC", "code", "", "(Script/SmcScript.js?version=)"},
	{"coremail", "code", "", "(/coremail/bundle/|contextRoot: \"/coremail\")"},
	{"activemq", "code", "", "(activemq_logo|Manage ActiveMQ broker)"},
	{"锐捷网络", "code", "", "(static/img/title.ico|support.ruijie.com.cn|Ruijie - NBR|eg.login.loginBtn|RG-EG易网关)"},
	{"禅道", "code", "", "(/theme/default/images/main/zt-logo.png|zentaosid)"},
	{"weblogic", "code", "", "(/console/framework/skins/wlsconsole/images/login_WebLogic_branding.png|Welcome to Weblogic Application Server|<i>Hypertext Transfer Protocol -- HTTP/1.1</i>|<TITLE>Error 404--Not Found</TITLE>|Welcome to Weblogic Application Server|<title>Oracle WebLogic Server 管理控制台</title>)"},
	{"weblogic", "headers", "", "(WebLogic)"},
	{"致远OA", "code", "", "(/seeyon/USER-DATA/IMAGES/LOGIN/login.gif|/seeyon/common/)"},
	{"蓝凌EIS智慧协同平台", "code", "", "(/scripts/jquery.landray.common.js)"},
	{"深信服系列", "code", "", "(login_psw.csp|loginPageSP/loginPrivacy.js|/por/login_psw.csp)"},
	{"Struts2", "code", "", "(org.apache.struts2|Struts Problem Report|struts.devMode|struts-tags|There is no Action mapped for namespace)"},
	{"泛微OA", "code", "", "(/spa/portal/public/index.js|wui/theme/ecology8/page/images/login/username_wev8.png|/wui/index.html#/?logintype=1)"},
	{"Swagger UI", "code", "", "(/swagger-ui.css|swagger-ui-bundle.js|swagger-ui-standalone-preset.js)"},
	{"金蝶政务GSiS", "code", "", "(/kdgs/script/kdgs.js|HTML5/content/themes/kdcss.min.css|/ClientBin/Kingdee.BOS.XPF.App.xap)"},
	{"蓝凌OA", "code", "", "(蓝凌软件|StylePath:\"/resource/style/default/\"|/resource/customization|sys/ui/extend/theme/default/style/icon.css|sys/ui/extend/theme/default/style/profile.css)"},
	{"用友NC", "code", "", "(YONYOU NC | /Client/Uclient/UClient.dmg)|yonyou-yyy.js|nc-lightapp-front/nc-lightapp-front.css|url=nccloud"},
	{"用友IUFO", "code", "", "(iufo/web/css/menu.css)"},
	{"TELEPORT堡垒机", "code", "", "(/static/plugins/blur/background-blur.js)"},
	{"JEECMS", "code", "", "(/r/cms/www/red/js/common.js|/r/cms/www/red/js/indexshow.js|Powered by JEECMS|JEECMS|/jeeadmin/jeecms/index.do)"},
	{"CMS", "code", "", "(Powered by .*CMS)"},
	{"Hashicorp", "code", "", "Consul by HashiCorp"},
	{"phpstudy", "code", "", "https://www.xp.cn"},
	{"Confluence", "code", "", "(confluence)"},
	{"hillstone", "code", "", "tac@hillstonenet.com"},
	{"Tomcat", "code", "", ">Apache Tomcat"},
	{"SVX8032", "code", "/cgi-bin/luci", "SVX8032"},
	{"econage", "code", "/wh/login.jsp", "/wh/js/validations.js"},
	{"axis2", "code", "/axis2", "administering"},
	{"docker", "code", "/version", "ApiVersion"},
	{"Kubernetes", "code", "", "(Kubernetes Dashboard</title>|Kubernetes Enterprise Manager|Mirantis Kubernetes Engine|Kubernetes Resource Report)"},
	{"RabbitMQ", "code", "", "RabbitMQ Management"},
	{"dubbo", "headers", "", "(Basic realm=\"dubbo\")"},
	{"SpringEureka", "code", "", "(eureka/css/wro.css)"},
	{"SpringbootActuator", "header", "/actuator", "spring-boot"},
	{"SpringbootEnv", "code", "/actuator/env", "(activeProfiles|propertySources)"},
	{"SpringbootEnv", "code", "/env", "(profiles|server.ports)"},
	{"gitlab", "code", "/git/users/sign_in", "(Sign in · GitLab)"},
	{"ueditor", "code", "", "(ueditor.all.js|UE.getEditor)"},
	{"亿邮电子邮件系统", "code", "", "(亿邮邮件整体解决方案|/tpl/public/js/eele.js)"},
	{"向日葵", "code", "", "({\"success\":false,\"msg\":\"Verification failure\"})"},
	{"Coremail", "code", "", "(Coremail System|http://www.coremail.cn)"},
}

var WebPort = []string{"80,81,82,83,84,85,86,87,88,89,90,91,92,98,99,443,800,801,808,880,888,889,1000,1010,1080,1081,1082,1118,1888,2008,2020,2100,2375,2379,3000,3008,3128,3505,5555,4430,6080,6648,6868,7000,7001,7002,7003,7004,7005,7007,7008,7070,7071,7074,7078,7080,7088,7200,7680,7687,7688,7777,7890,8000,8001,8002,8003,8004,8006,8008,8009,8010,8011,8012,8016,8018,8020,8028,8030,8038,8042,8044,8046,8048,8053,8060,8069,8070,8080,8081,8082,8083,8084,8085,8086,8087,8088,8089,8090,8091,8092,8093,8094,8095,8096,8097,8098,8099,8100,8101,8108,8118,8161,8172,8180,8181,8200,8222,8244,8258,8280,8288,8300,8360,8443,8448,8484,8800,8834,8838,8848,8858,8868,8879,8880,8881,8888,8899,8983,8989,9000,9001,9002,9008,9010,9043,9060,9080,9081,9082,9083,9084,9085,9086,9087,9088,9089,9090,9091,9092,9093,9094,9095,9096,9097,9098,9099,9100,9200,9443,9448,9800,9981,9986,9988,9998,9999,10000,10001,10002,10004,10008,10010,10250,12018,12443,14000,16080,18000,18001,18002,18004,18008,18080,18082,18088,18090,18098,19001,20000,20720,21000,21501,21502,28018,20880"}

var FtpDic = map[string][]string{
	"port": {"21"},
	"user": {"ftp", "root"},
	"pass": {"123456", "password", "123", "{{user}}", "{{user}}123", "{{user}}@123", "{{user}}2021", "{{user}}2022", "P@ssw0rd", "qwer1234", "1qaz2wsx", "1qaz2wsx3edc", "1qaz@wsx"},
}

var MysqlDic = map[string][]string{
	"port": {"3306"},
	"user": {"root", "mysql"},
	"pass": {"123456", "password", "123", "{{user}}", "{{user}}123", "{{user}}@123", "{{user}}2021", "{{user}}2022", "P@ssw0rd", "qwer1234", "1qaz2wsx", "1qaz2wsx3edc", "1qaz@wsx"},
}

var MssqlDic = map[string][]string{
	"port": {"1433"},
	"user": {"sa", "root"},
	"pass": {"123456", "password", "123", "{{user}}", "{{user}}123", "{{user}}@123", "{{user}}2021", "{{user}}2022", "P@ssw0rd", "qwer1234", "1qaz2wsx", "1qaz2wsx3edc", "1qaz@wsx"},
}

var SmbDic = map[string][]string{
	"port": {"445"},
	"user": {"administrator", "admin"},
	"pass": {"123456", "password", "123", "{{user}}", "{{user}}123", "{{user}}@123", "{{user}}2021", "{{user}}2022", "P@ssw0rd", "qwer1234", "1qaz2wsx", "1qaz2wsx3edc", "1qaz@wsx"},
}

var RdpDic = map[string][]string{
	"port": {"3389"},
	"user": {"administrator", "admin"},
	"pass": {"{{user}}@123456", "{{user}}@2019", "{{user}}@2020", "{{user}}@2021", "!QAZ2wsx", "1qaz2wsx", "1qaz@WSX", "1qaz!QAZ", "2wsx@WSX", "Aa123456!"},
}

var PostgreDic = map[string][]string{
	"port": {"5432"},
	"user": {"root", "postgres"},
	"pass": {"123456", "password", "123", "{{user}}", "{{user}}123", "{{user}}@123", "{{user}}2021", "{{user}}2022", "P@ssw0rd", "qwer1234", "1qaz2wsx", "1qaz2wsx3edc", "1qaz@wsx"},
}

var SshDic = map[string][]string{
	"port": {"22"},
	"user": {"root", "admin"},
	"pass": {"123456", "password", "123", "{{user}}", "{{user}}123", "{{user}}@123", "{{user}}2021", "{{user}}2022", "P@ssw0rd", "qwer1234", "1qaz2wsx", "1qaz2wsx3edc", "1qaz@wsx"},
}

var TelnetDic = map[string][]string{
	"port": {"23"},
	"user": {"root", "admin"},
	"pass": {"123456", "password", "123", "{{user}}", "{{user}}123", "{{user}}@123", "{{user}}2021", "{{user}}2022", "P@ssw0rd", "qwer1234", "1qaz2wsx", "1qaz2wsx3edc", "1qaz@wsx"},
}

var RedisDic = map[string][]string{
	"port": {"6379"},
	"pass": {"123456", "password", "123", "{{user}}", "{{user}}123", "{{user}}@123", "{{user}}2021", "{{user}}2022", "P@ssw0rd", "qwer1234", "1qaz2wsx", "1qaz2wsx3edc", "1qaz@wsx"},
}

var TomcatDic = map[string][]string{
	"user": {"tomcat", "admin", "manager"},
	"pass": {"123456", "{{user}}", "{{user}}123", "password", "pass", "s3cret"},
}

var NetBiosPort = []string{"135", "139"}
